# merge the default 'Exclude' key with ours
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rspec
  - rubocop-minitest
  - rubocop-packaging

AllCops:
  NewCops: enable
  StyleGuideBaseURL: https://rubystyle.guide
  TargetRubyVersion: 3.0
  SuggestExtensions: false # reduce noise. consider add rubocop-benchmark

  Exclude:
    - bin/**/*
    - tmp/**/*

Bundler/OrderedGems:
  Include:
    - '*.gemspec'

# Allow no documentation.
Style/Documentation:
  Enabled: false

# Enforce single quotes in the gem
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys # consistent hash syntax
  EnforcedShorthandSyntax: consistent # enforce explicit hash syntax

# Enforce dots on the next line for multi-line method calls
Layout/DotPosition:
  EnforcedStyle: trailing

# Project maximum code line length
Layout/LineLength:
  Max: 120

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/SymbolArray:
  EnforcedStyle: brackets # Prefer brackets

Style/WordArray:
  EnforcedStyle: brackets # Prefer brackets

Style/FrozenStringLiteralComment:
  Enabled: false

# Exclude test files from BlockComments check
Style/BlockComments:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 500

Metrics/BlockLength:
  Max: 50
  Exclude:
    # allows longer block for RSpec
    - spec/**/*.rb

Metrics/AbcSize:
  Max: 110

Metrics/BlockNesting:
  Max: 5

Metrics/CyclomaticComplexity:
  Max: 40

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 250
  Exclude:
    # allows longer block for RSpec
    - spec/**/*.rb
    - lib/ffi-icu/lib.rb

Metrics/PerceivedComplexity:
  Max: 50

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/ffi-icu.rb
