/* automatically generated by rust-bindgen 0.72.1 */

pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __uint_least16_t = __uint16_t;
pub type char16_t = __uint_least16_t;
pub type UBool = i8;
pub type UChar = char16_t;
pub type UVersionInfo = [u8; 4usize];
pub type UDate = f64;
impl UErrorCode {
    pub const U_USING_FALLBACK_WARNING: UErrorCode = UErrorCode(-128);
    pub const U_ERROR_WARNING_START: UErrorCode = UErrorCode(-128);
    pub const U_USING_DEFAULT_WARNING: UErrorCode = UErrorCode(-127);
    pub const U_SAFECLONE_ALLOCATED_WARNING: UErrorCode = UErrorCode(-126);
    pub const U_STATE_OLD_WARNING: UErrorCode = UErrorCode(-125);
    pub const U_STRING_NOT_TERMINATED_WARNING: UErrorCode = UErrorCode(-124);
    pub const U_SORT_KEY_TOO_SHORT_WARNING: UErrorCode = UErrorCode(-123);
    pub const U_AMBIGUOUS_ALIAS_WARNING: UErrorCode = UErrorCode(-122);
    pub const U_DIFFERENT_UCA_VERSION: UErrorCode = UErrorCode(-121);
    pub const U_PLUGIN_CHANGED_LEVEL_WARNING: UErrorCode = UErrorCode(-120);
    pub const U_ERROR_WARNING_LIMIT: UErrorCode = UErrorCode(-119);
    pub const U_ZERO_ERROR: UErrorCode = UErrorCode(0);
    pub const U_ILLEGAL_ARGUMENT_ERROR: UErrorCode = UErrorCode(1);
    pub const U_MISSING_RESOURCE_ERROR: UErrorCode = UErrorCode(2);
    pub const U_INVALID_FORMAT_ERROR: UErrorCode = UErrorCode(3);
    pub const U_FILE_ACCESS_ERROR: UErrorCode = UErrorCode(4);
    pub const U_INTERNAL_PROGRAM_ERROR: UErrorCode = UErrorCode(5);
    pub const U_MESSAGE_PARSE_ERROR: UErrorCode = UErrorCode(6);
    pub const U_MEMORY_ALLOCATION_ERROR: UErrorCode = UErrorCode(7);
    pub const U_INDEX_OUTOFBOUNDS_ERROR: UErrorCode = UErrorCode(8);
    pub const U_PARSE_ERROR: UErrorCode = UErrorCode(9);
    pub const U_INVALID_CHAR_FOUND: UErrorCode = UErrorCode(10);
    pub const U_TRUNCATED_CHAR_FOUND: UErrorCode = UErrorCode(11);
    pub const U_ILLEGAL_CHAR_FOUND: UErrorCode = UErrorCode(12);
    pub const U_INVALID_TABLE_FORMAT: UErrorCode = UErrorCode(13);
    pub const U_INVALID_TABLE_FILE: UErrorCode = UErrorCode(14);
    pub const U_BUFFER_OVERFLOW_ERROR: UErrorCode = UErrorCode(15);
    pub const U_UNSUPPORTED_ERROR: UErrorCode = UErrorCode(16);
    pub const U_RESOURCE_TYPE_MISMATCH: UErrorCode = UErrorCode(17);
    pub const U_ILLEGAL_ESCAPE_SEQUENCE: UErrorCode = UErrorCode(18);
    pub const U_UNSUPPORTED_ESCAPE_SEQUENCE: UErrorCode = UErrorCode(19);
    pub const U_NO_SPACE_AVAILABLE: UErrorCode = UErrorCode(20);
    pub const U_CE_NOT_FOUND_ERROR: UErrorCode = UErrorCode(21);
    pub const U_PRIMARY_TOO_LONG_ERROR: UErrorCode = UErrorCode(22);
    pub const U_STATE_TOO_OLD_ERROR: UErrorCode = UErrorCode(23);
    pub const U_TOO_MANY_ALIASES_ERROR: UErrorCode = UErrorCode(24);
    pub const U_ENUM_OUT_OF_SYNC_ERROR: UErrorCode = UErrorCode(25);
    pub const U_INVARIANT_CONVERSION_ERROR: UErrorCode = UErrorCode(26);
    pub const U_INVALID_STATE_ERROR: UErrorCode = UErrorCode(27);
    pub const U_COLLATOR_VERSION_MISMATCH: UErrorCode = UErrorCode(28);
    pub const U_USELESS_COLLATOR_ERROR: UErrorCode = UErrorCode(29);
    pub const U_NO_WRITE_PERMISSION: UErrorCode = UErrorCode(30);
    pub const U_INPUT_TOO_LONG_ERROR: UErrorCode = UErrorCode(31);
    pub const U_STANDARD_ERROR_LIMIT: UErrorCode = UErrorCode(32);
    pub const U_BAD_VARIABLE_DEFINITION: UErrorCode = UErrorCode(65536);
    pub const U_PARSE_ERROR_START: UErrorCode = UErrorCode(65536);
    pub const U_MALFORMED_RULE: UErrorCode = UErrorCode(65537);
    pub const U_MALFORMED_SET: UErrorCode = UErrorCode(65538);
    pub const U_MALFORMED_SYMBOL_REFERENCE: UErrorCode = UErrorCode(65539);
    pub const U_MALFORMED_UNICODE_ESCAPE: UErrorCode = UErrorCode(65540);
    pub const U_MALFORMED_VARIABLE_DEFINITION: UErrorCode = UErrorCode(65541);
    pub const U_MALFORMED_VARIABLE_REFERENCE: UErrorCode = UErrorCode(65542);
    pub const U_MISMATCHED_SEGMENT_DELIMITERS: UErrorCode = UErrorCode(65543);
    pub const U_MISPLACED_ANCHOR_START: UErrorCode = UErrorCode(65544);
    pub const U_MISPLACED_CURSOR_OFFSET: UErrorCode = UErrorCode(65545);
    pub const U_MISPLACED_QUANTIFIER: UErrorCode = UErrorCode(65546);
    pub const U_MISSING_OPERATOR: UErrorCode = UErrorCode(65547);
    pub const U_MISSING_SEGMENT_CLOSE: UErrorCode = UErrorCode(65548);
    pub const U_MULTIPLE_ANTE_CONTEXTS: UErrorCode = UErrorCode(65549);
    pub const U_MULTIPLE_CURSORS: UErrorCode = UErrorCode(65550);
    pub const U_MULTIPLE_POST_CONTEXTS: UErrorCode = UErrorCode(65551);
    pub const U_TRAILING_BACKSLASH: UErrorCode = UErrorCode(65552);
    pub const U_UNDEFINED_SEGMENT_REFERENCE: UErrorCode = UErrorCode(65553);
    pub const U_UNDEFINED_VARIABLE: UErrorCode = UErrorCode(65554);
    pub const U_UNQUOTED_SPECIAL: UErrorCode = UErrorCode(65555);
    pub const U_UNTERMINATED_QUOTE: UErrorCode = UErrorCode(65556);
    pub const U_RULE_MASK_ERROR: UErrorCode = UErrorCode(65557);
    pub const U_MISPLACED_COMPOUND_FILTER: UErrorCode = UErrorCode(65558);
    pub const U_MULTIPLE_COMPOUND_FILTERS: UErrorCode = UErrorCode(65559);
    pub const U_INVALID_RBT_SYNTAX: UErrorCode = UErrorCode(65560);
    pub const U_INVALID_PROPERTY_PATTERN: UErrorCode = UErrorCode(65561);
    pub const U_MALFORMED_PRAGMA: UErrorCode = UErrorCode(65562);
    pub const U_UNCLOSED_SEGMENT: UErrorCode = UErrorCode(65563);
    pub const U_ILLEGAL_CHAR_IN_SEGMENT: UErrorCode = UErrorCode(65564);
    pub const U_VARIABLE_RANGE_EXHAUSTED: UErrorCode = UErrorCode(65565);
    pub const U_VARIABLE_RANGE_OVERLAP: UErrorCode = UErrorCode(65566);
    pub const U_ILLEGAL_CHARACTER: UErrorCode = UErrorCode(65567);
    pub const U_INTERNAL_TRANSLITERATOR_ERROR: UErrorCode = UErrorCode(65568);
    pub const U_INVALID_ID: UErrorCode = UErrorCode(65569);
    pub const U_INVALID_FUNCTION: UErrorCode = UErrorCode(65570);
    pub const U_PARSE_ERROR_LIMIT: UErrorCode = UErrorCode(65571);
    pub const U_UNEXPECTED_TOKEN: UErrorCode = UErrorCode(65792);
    pub const U_FMT_PARSE_ERROR_START: UErrorCode = UErrorCode(65792);
    pub const U_MULTIPLE_DECIMAL_SEPARATORS: UErrorCode = UErrorCode(65793);
    pub const U_MULTIPLE_DECIMAL_SEPERATORS: UErrorCode = UErrorCode(65793);
    pub const U_MULTIPLE_EXPONENTIAL_SYMBOLS: UErrorCode = UErrorCode(65794);
    pub const U_MALFORMED_EXPONENTIAL_PATTERN: UErrorCode = UErrorCode(65795);
    pub const U_MULTIPLE_PERCENT_SYMBOLS: UErrorCode = UErrorCode(65796);
    pub const U_MULTIPLE_PERMILL_SYMBOLS: UErrorCode = UErrorCode(65797);
    pub const U_MULTIPLE_PAD_SPECIFIERS: UErrorCode = UErrorCode(65798);
    pub const U_PATTERN_SYNTAX_ERROR: UErrorCode = UErrorCode(65799);
    pub const U_ILLEGAL_PAD_POSITION: UErrorCode = UErrorCode(65800);
    pub const U_UNMATCHED_BRACES: UErrorCode = UErrorCode(65801);
    pub const U_UNSUPPORTED_PROPERTY: UErrorCode = UErrorCode(65802);
    pub const U_UNSUPPORTED_ATTRIBUTE: UErrorCode = UErrorCode(65803);
    pub const U_ARGUMENT_TYPE_MISMATCH: UErrorCode = UErrorCode(65804);
    pub const U_DUPLICATE_KEYWORD: UErrorCode = UErrorCode(65805);
    pub const U_UNDEFINED_KEYWORD: UErrorCode = UErrorCode(65806);
    pub const U_DEFAULT_KEYWORD_MISSING: UErrorCode = UErrorCode(65807);
    pub const U_DECIMAL_NUMBER_SYNTAX_ERROR: UErrorCode = UErrorCode(65808);
    pub const U_FORMAT_INEXACT_ERROR: UErrorCode = UErrorCode(65809);
    pub const U_NUMBER_ARG_OUTOFBOUNDS_ERROR: UErrorCode = UErrorCode(65810);
    pub const U_NUMBER_SKELETON_SYNTAX_ERROR: UErrorCode = UErrorCode(65811);
    pub const U_MF_UNRESOLVED_VARIABLE_ERROR: UErrorCode = UErrorCode(65812);
    pub const U_MF_SYNTAX_ERROR: UErrorCode = UErrorCode(65813);
    pub const U_MF_UNKNOWN_FUNCTION_ERROR: UErrorCode = UErrorCode(65814);
    pub const U_MF_VARIANT_KEY_MISMATCH_ERROR: UErrorCode = UErrorCode(65815);
    pub const U_MF_FORMATTING_ERROR: UErrorCode = UErrorCode(65816);
    pub const U_MF_NONEXHAUSTIVE_PATTERN_ERROR: UErrorCode = UErrorCode(65817);
    pub const U_MF_DUPLICATE_OPTION_NAME_ERROR: UErrorCode = UErrorCode(65818);
    pub const U_MF_SELECTOR_ERROR: UErrorCode = UErrorCode(65819);
    pub const U_MF_MISSING_SELECTOR_ANNOTATION_ERROR: UErrorCode = UErrorCode(65820);
    pub const U_MF_DUPLICATE_DECLARATION_ERROR: UErrorCode = UErrorCode(65821);
    pub const U_MF_OPERAND_MISMATCH_ERROR: UErrorCode = UErrorCode(65822);
    pub const U_MF_DUPLICATE_VARIANT_ERROR: UErrorCode = UErrorCode(65823);
    pub const U_MF_BAD_OPTION: UErrorCode = UErrorCode(65824);
    pub const U_FMT_PARSE_ERROR_LIMIT: UErrorCode = UErrorCode(65825);
    pub const U_BRK_INTERNAL_ERROR: UErrorCode = UErrorCode(66048);
    pub const U_BRK_ERROR_START: UErrorCode = UErrorCode(66048);
    pub const U_BRK_HEX_DIGITS_EXPECTED: UErrorCode = UErrorCode(66049);
    pub const U_BRK_SEMICOLON_EXPECTED: UErrorCode = UErrorCode(66050);
    pub const U_BRK_RULE_SYNTAX: UErrorCode = UErrorCode(66051);
    pub const U_BRK_UNCLOSED_SET: UErrorCode = UErrorCode(66052);
    pub const U_BRK_ASSIGN_ERROR: UErrorCode = UErrorCode(66053);
    pub const U_BRK_VARIABLE_REDFINITION: UErrorCode = UErrorCode(66054);
    pub const U_BRK_MISMATCHED_PAREN: UErrorCode = UErrorCode(66055);
    pub const U_BRK_NEW_LINE_IN_QUOTED_STRING: UErrorCode = UErrorCode(66056);
    pub const U_BRK_UNDEFINED_VARIABLE: UErrorCode = UErrorCode(66057);
    pub const U_BRK_INIT_ERROR: UErrorCode = UErrorCode(66058);
    pub const U_BRK_RULE_EMPTY_SET: UErrorCode = UErrorCode(66059);
    pub const U_BRK_UNRECOGNIZED_OPTION: UErrorCode = UErrorCode(66060);
    pub const U_BRK_MALFORMED_RULE_TAG: UErrorCode = UErrorCode(66061);
    pub const U_BRK_ERROR_LIMIT: UErrorCode = UErrorCode(66062);
    pub const U_REGEX_INTERNAL_ERROR: UErrorCode = UErrorCode(66304);
    pub const U_REGEX_ERROR_START: UErrorCode = UErrorCode(66304);
    pub const U_REGEX_RULE_SYNTAX: UErrorCode = UErrorCode(66305);
    pub const U_REGEX_INVALID_STATE: UErrorCode = UErrorCode(66306);
    pub const U_REGEX_BAD_ESCAPE_SEQUENCE: UErrorCode = UErrorCode(66307);
    pub const U_REGEX_PROPERTY_SYNTAX: UErrorCode = UErrorCode(66308);
    pub const U_REGEX_UNIMPLEMENTED: UErrorCode = UErrorCode(66309);
    pub const U_REGEX_MISMATCHED_PAREN: UErrorCode = UErrorCode(66310);
    pub const U_REGEX_NUMBER_TOO_BIG: UErrorCode = UErrorCode(66311);
    pub const U_REGEX_BAD_INTERVAL: UErrorCode = UErrorCode(66312);
    pub const U_REGEX_MAX_LT_MIN: UErrorCode = UErrorCode(66313);
    pub const U_REGEX_INVALID_BACK_REF: UErrorCode = UErrorCode(66314);
    pub const U_REGEX_INVALID_FLAG: UErrorCode = UErrorCode(66315);
    pub const U_REGEX_LOOK_BEHIND_LIMIT: UErrorCode = UErrorCode(66316);
    pub const U_REGEX_SET_CONTAINS_STRING: UErrorCode = UErrorCode(66317);
    pub const U_REGEX_OCTAL_TOO_BIG: UErrorCode = UErrorCode(66318);
    pub const U_REGEX_MISSING_CLOSE_BRACKET: UErrorCode = UErrorCode(66319);
    pub const U_REGEX_INVALID_RANGE: UErrorCode = UErrorCode(66320);
    pub const U_REGEX_STACK_OVERFLOW: UErrorCode = UErrorCode(66321);
    pub const U_REGEX_TIME_OUT: UErrorCode = UErrorCode(66322);
    pub const U_REGEX_STOPPED_BY_CALLER: UErrorCode = UErrorCode(66323);
    pub const U_REGEX_PATTERN_TOO_BIG: UErrorCode = UErrorCode(66324);
    pub const U_REGEX_INVALID_CAPTURE_GROUP_NAME: UErrorCode = UErrorCode(66325);
    pub const U_REGEX_ERROR_LIMIT: UErrorCode = UErrorCode(66326);
    pub const U_IDNA_PROHIBITED_ERROR: UErrorCode = UErrorCode(66560);
    pub const U_IDNA_ERROR_START: UErrorCode = UErrorCode(66560);
    pub const U_IDNA_UNASSIGNED_ERROR: UErrorCode = UErrorCode(66561);
    pub const U_IDNA_CHECK_BIDI_ERROR: UErrorCode = UErrorCode(66562);
    pub const U_IDNA_STD3_ASCII_RULES_ERROR: UErrorCode = UErrorCode(66563);
    pub const U_IDNA_ACE_PREFIX_ERROR: UErrorCode = UErrorCode(66564);
    pub const U_IDNA_VERIFICATION_ERROR: UErrorCode = UErrorCode(66565);
    pub const U_IDNA_LABEL_TOO_LONG_ERROR: UErrorCode = UErrorCode(66566);
    pub const U_IDNA_ZERO_LENGTH_LABEL_ERROR: UErrorCode = UErrorCode(66567);
    pub const U_IDNA_DOMAIN_NAME_TOO_LONG_ERROR: UErrorCode = UErrorCode(66568);
    pub const U_IDNA_ERROR_LIMIT: UErrorCode = UErrorCode(66569);
    pub const U_STRINGPREP_PROHIBITED_ERROR: UErrorCode = UErrorCode(66560);
    pub const U_STRINGPREP_UNASSIGNED_ERROR: UErrorCode = UErrorCode(66561);
    pub const U_STRINGPREP_CHECK_BIDI_ERROR: UErrorCode = UErrorCode(66562);
    pub const U_PLUGIN_ERROR_START: UErrorCode = UErrorCode(66816);
    pub const U_PLUGIN_TOO_HIGH: UErrorCode = UErrorCode(66816);
    pub const U_PLUGIN_DIDNT_SET_LEVEL: UErrorCode = UErrorCode(66817);
    pub const U_PLUGIN_ERROR_LIMIT: UErrorCode = UErrorCode(66818);
    pub const U_ERROR_LIMIT: UErrorCode = UErrorCode(66818);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UErrorCode(pub ::std::os::raw::c_int);
pub type UCalendar = *mut ::std::os::raw::c_void;
impl UCalendarType {
    pub const UCAL_TRADITIONAL: UCalendarType = UCalendarType(0);
    pub const UCAL_DEFAULT: UCalendarType = UCalendarType(0);
    pub const UCAL_GREGORIAN: UCalendarType = UCalendarType(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarType(pub ::std::os::raw::c_uint);
impl UCalendarDateFields {
    pub const UCAL_ERA: UCalendarDateFields = UCalendarDateFields(0);
    pub const UCAL_YEAR: UCalendarDateFields = UCalendarDateFields(1);
    pub const UCAL_MONTH: UCalendarDateFields = UCalendarDateFields(2);
    pub const UCAL_WEEK_OF_YEAR: UCalendarDateFields = UCalendarDateFields(3);
    pub const UCAL_WEEK_OF_MONTH: UCalendarDateFields = UCalendarDateFields(4);
    pub const UCAL_DATE: UCalendarDateFields = UCalendarDateFields(5);
    pub const UCAL_DAY_OF_YEAR: UCalendarDateFields = UCalendarDateFields(6);
    pub const UCAL_DAY_OF_WEEK: UCalendarDateFields = UCalendarDateFields(7);
    pub const UCAL_DAY_OF_WEEK_IN_MONTH: UCalendarDateFields = UCalendarDateFields(8);
    pub const UCAL_AM_PM: UCalendarDateFields = UCalendarDateFields(9);
    pub const UCAL_HOUR: UCalendarDateFields = UCalendarDateFields(10);
    pub const UCAL_HOUR_OF_DAY: UCalendarDateFields = UCalendarDateFields(11);
    pub const UCAL_MINUTE: UCalendarDateFields = UCalendarDateFields(12);
    pub const UCAL_SECOND: UCalendarDateFields = UCalendarDateFields(13);
    pub const UCAL_MILLISECOND: UCalendarDateFields = UCalendarDateFields(14);
    pub const UCAL_ZONE_OFFSET: UCalendarDateFields = UCalendarDateFields(15);
    pub const UCAL_DST_OFFSET: UCalendarDateFields = UCalendarDateFields(16);
    pub const UCAL_YEAR_WOY: UCalendarDateFields = UCalendarDateFields(17);
    pub const UCAL_DOW_LOCAL: UCalendarDateFields = UCalendarDateFields(18);
    pub const UCAL_EXTENDED_YEAR: UCalendarDateFields = UCalendarDateFields(19);
    pub const UCAL_JULIAN_DAY: UCalendarDateFields = UCalendarDateFields(20);
    pub const UCAL_MILLISECONDS_IN_DAY: UCalendarDateFields = UCalendarDateFields(21);
    pub const UCAL_IS_LEAP_MONTH: UCalendarDateFields = UCalendarDateFields(22);
    pub const UCAL_ORDINAL_MONTH: UCalendarDateFields = UCalendarDateFields(23);
    pub const UCAL_FIELD_COUNT: UCalendarDateFields = UCalendarDateFields(24);
    pub const UCAL_DAY_OF_MONTH: UCalendarDateFields = UCalendarDateFields(5);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarDateFields(pub ::std::os::raw::c_uint);
impl UCalendarDaysOfWeek {
    pub const UCAL_SUNDAY: UCalendarDaysOfWeek = UCalendarDaysOfWeek(1);
    pub const UCAL_MONDAY: UCalendarDaysOfWeek = UCalendarDaysOfWeek(2);
    pub const UCAL_TUESDAY: UCalendarDaysOfWeek = UCalendarDaysOfWeek(3);
    pub const UCAL_WEDNESDAY: UCalendarDaysOfWeek = UCalendarDaysOfWeek(4);
    pub const UCAL_THURSDAY: UCalendarDaysOfWeek = UCalendarDaysOfWeek(5);
    pub const UCAL_FRIDAY: UCalendarDaysOfWeek = UCalendarDaysOfWeek(6);
    pub const UCAL_SATURDAY: UCalendarDaysOfWeek = UCalendarDaysOfWeek(7);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarDaysOfWeek(pub ::std::os::raw::c_uint);
impl UCalendarMonths {
    pub const UCAL_JANUARY: UCalendarMonths = UCalendarMonths(0);
    pub const UCAL_FEBRUARY: UCalendarMonths = UCalendarMonths(1);
    pub const UCAL_MARCH: UCalendarMonths = UCalendarMonths(2);
    pub const UCAL_APRIL: UCalendarMonths = UCalendarMonths(3);
    pub const UCAL_MAY: UCalendarMonths = UCalendarMonths(4);
    pub const UCAL_JUNE: UCalendarMonths = UCalendarMonths(5);
    pub const UCAL_JULY: UCalendarMonths = UCalendarMonths(6);
    pub const UCAL_AUGUST: UCalendarMonths = UCalendarMonths(7);
    pub const UCAL_SEPTEMBER: UCalendarMonths = UCalendarMonths(8);
    pub const UCAL_OCTOBER: UCalendarMonths = UCalendarMonths(9);
    pub const UCAL_NOVEMBER: UCalendarMonths = UCalendarMonths(10);
    pub const UCAL_DECEMBER: UCalendarMonths = UCalendarMonths(11);
    pub const UCAL_UNDECIMBER: UCalendarMonths = UCalendarMonths(12);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarMonths(pub ::std::os::raw::c_uint);
impl UCalendarAMPMs {
    pub const UCAL_AM: UCalendarAMPMs = UCalendarAMPMs(0);
    pub const UCAL_PM: UCalendarAMPMs = UCalendarAMPMs(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarAMPMs(pub ::std::os::raw::c_uint);
impl UCalendarDisplayNameType {
    pub const UCAL_STANDARD: UCalendarDisplayNameType = UCalendarDisplayNameType(0);
    pub const UCAL_SHORT_STANDARD: UCalendarDisplayNameType = UCalendarDisplayNameType(1);
    pub const UCAL_DST: UCalendarDisplayNameType = UCalendarDisplayNameType(2);
    pub const UCAL_SHORT_DST: UCalendarDisplayNameType = UCalendarDisplayNameType(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarDisplayNameType(pub ::std::os::raw::c_uint);
impl UCalendarAttribute {
    pub const UCAL_LENIENT: UCalendarAttribute = UCalendarAttribute(0);
    pub const UCAL_FIRST_DAY_OF_WEEK: UCalendarAttribute = UCalendarAttribute(1);
    pub const UCAL_MINIMAL_DAYS_IN_FIRST_WEEK: UCalendarAttribute = UCalendarAttribute(2);
    pub const UCAL_REPEATED_WALL_TIME: UCalendarAttribute = UCalendarAttribute(3);
    pub const UCAL_SKIPPED_WALL_TIME: UCalendarAttribute = UCalendarAttribute(4);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarAttribute(pub ::std::os::raw::c_uint);
impl UCalendarWallTimeOption {
    pub const UCAL_WALLTIME_LAST: UCalendarWallTimeOption = UCalendarWallTimeOption(0);
    pub const UCAL_WALLTIME_FIRST: UCalendarWallTimeOption = UCalendarWallTimeOption(1);
    pub const UCAL_WALLTIME_NEXT_VALID: UCalendarWallTimeOption = UCalendarWallTimeOption(2);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarWallTimeOption(pub ::std::os::raw::c_uint);
impl UCalendarLimitType {
    pub const UCAL_MINIMUM: UCalendarLimitType = UCalendarLimitType(0);
    pub const UCAL_MAXIMUM: UCalendarLimitType = UCalendarLimitType(1);
    pub const UCAL_GREATEST_MINIMUM: UCalendarLimitType = UCalendarLimitType(2);
    pub const UCAL_LEAST_MAXIMUM: UCalendarLimitType = UCalendarLimitType(3);
    pub const UCAL_ACTUAL_MINIMUM: UCalendarLimitType = UCalendarLimitType(4);
    pub const UCAL_ACTUAL_MAXIMUM: UCalendarLimitType = UCalendarLimitType(5);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarLimitType(pub ::std::os::raw::c_uint);
impl UCalendarWeekdayType {
    pub const UCAL_WEEKDAY: UCalendarWeekdayType = UCalendarWeekdayType(0);
    pub const UCAL_WEEKEND: UCalendarWeekdayType = UCalendarWeekdayType(1);
    pub const UCAL_WEEKEND_ONSET: UCalendarWeekdayType = UCalendarWeekdayType(2);
    pub const UCAL_WEEKEND_CEASE: UCalendarWeekdayType = UCalendarWeekdayType(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UCalendarWeekdayType(pub ::std::os::raw::c_uint);
impl UNumberFormatRoundingMode {
    pub const UNUM_ROUND_CEILING: UNumberFormatRoundingMode = UNumberFormatRoundingMode(0);
    pub const UNUM_ROUND_FLOOR: UNumberFormatRoundingMode = UNumberFormatRoundingMode(1);
    pub const UNUM_ROUND_DOWN: UNumberFormatRoundingMode = UNumberFormatRoundingMode(2);
    pub const UNUM_ROUND_UP: UNumberFormatRoundingMode = UNumberFormatRoundingMode(3);
    pub const UNUM_ROUND_HALFEVEN: UNumberFormatRoundingMode = UNumberFormatRoundingMode(4);
    pub const UNUM_FOUND_HALFEVEN: UNumberFormatRoundingMode = UNumberFormatRoundingMode(4);
    pub const UNUM_ROUND_HALFDOWN: UNumberFormatRoundingMode = UNumberFormatRoundingMode(5);
    pub const UNUM_ROUND_HALFUP: UNumberFormatRoundingMode = UNumberFormatRoundingMode(6);
    pub const UNUM_ROUND_UNNECESSARY: UNumberFormatRoundingMode = UNumberFormatRoundingMode(7);
    pub const UNUM_ROUND_HALF_ODD: UNumberFormatRoundingMode = UNumberFormatRoundingMode(8);
    pub const UNUM_ROUND_HALF_CEILING: UNumberFormatRoundingMode = UNumberFormatRoundingMode(9);
    pub const UNUM_ROUND_HALF_FLOOR: UNumberFormatRoundingMode = UNumberFormatRoundingMode(10);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatRoundingMode(pub ::std::os::raw::c_uint);
pub type UNumberFormat = *mut ::std::os::raw::c_void;
impl UNumberFormatStyle {
    pub const UNUM_PATTERN_DECIMAL: UNumberFormatStyle = UNumberFormatStyle(0);
    pub const UNUM_DECIMAL: UNumberFormatStyle = UNumberFormatStyle(1);
    pub const UNUM_CURRENCY: UNumberFormatStyle = UNumberFormatStyle(2);
    pub const UNUM_PERCENT: UNumberFormatStyle = UNumberFormatStyle(3);
    pub const UNUM_SCIENTIFIC: UNumberFormatStyle = UNumberFormatStyle(4);
    pub const UNUM_SPELLOUT: UNumberFormatStyle = UNumberFormatStyle(5);
    pub const UNUM_ORDINAL: UNumberFormatStyle = UNumberFormatStyle(6);
    pub const UNUM_DURATION: UNumberFormatStyle = UNumberFormatStyle(7);
    pub const UNUM_NUMBERING_SYSTEM: UNumberFormatStyle = UNumberFormatStyle(8);
    pub const UNUM_PATTERN_RULEBASED: UNumberFormatStyle = UNumberFormatStyle(9);
    pub const UNUM_CURRENCY_ISO: UNumberFormatStyle = UNumberFormatStyle(10);
    pub const UNUM_CURRENCY_PLURAL: UNumberFormatStyle = UNumberFormatStyle(11);
    pub const UNUM_CURRENCY_ACCOUNTING: UNumberFormatStyle = UNumberFormatStyle(12);
    pub const UNUM_CASH_CURRENCY: UNumberFormatStyle = UNumberFormatStyle(13);
    pub const UNUM_DECIMAL_COMPACT_SHORT: UNumberFormatStyle = UNumberFormatStyle(14);
    pub const UNUM_DECIMAL_COMPACT_LONG: UNumberFormatStyle = UNumberFormatStyle(15);
    pub const UNUM_CURRENCY_STANDARD: UNumberFormatStyle = UNumberFormatStyle(16);
    pub const UNUM_FORMAT_STYLE_COUNT: UNumberFormatStyle = UNumberFormatStyle(17);
    pub const UNUM_DEFAULT: UNumberFormatStyle = UNumberFormatStyle(1);
    pub const UNUM_IGNORE: UNumberFormatStyle = UNumberFormatStyle(0);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatStyle(pub ::std::os::raw::c_uint);
impl UNumberFormatPadPosition {
    pub const UNUM_PAD_BEFORE_PREFIX: UNumberFormatPadPosition = UNumberFormatPadPosition(0);
    pub const UNUM_PAD_AFTER_PREFIX: UNumberFormatPadPosition = UNumberFormatPadPosition(1);
    pub const UNUM_PAD_BEFORE_SUFFIX: UNumberFormatPadPosition = UNumberFormatPadPosition(2);
    pub const UNUM_PAD_AFTER_SUFFIX: UNumberFormatPadPosition = UNumberFormatPadPosition(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatPadPosition(pub ::std::os::raw::c_uint);
impl UNumberFormatFields {
    pub const UNUM_INTEGER_FIELD: UNumberFormatFields = UNumberFormatFields(0);
    pub const UNUM_FRACTION_FIELD: UNumberFormatFields = UNumberFormatFields(1);
    pub const UNUM_DECIMAL_SEPARATOR_FIELD: UNumberFormatFields = UNumberFormatFields(2);
    pub const UNUM_EXPONENT_SYMBOL_FIELD: UNumberFormatFields = UNumberFormatFields(3);
    pub const UNUM_EXPONENT_SIGN_FIELD: UNumberFormatFields = UNumberFormatFields(4);
    pub const UNUM_EXPONENT_FIELD: UNumberFormatFields = UNumberFormatFields(5);
    pub const UNUM_GROUPING_SEPARATOR_FIELD: UNumberFormatFields = UNumberFormatFields(6);
    pub const UNUM_CURRENCY_FIELD: UNumberFormatFields = UNumberFormatFields(7);
    pub const UNUM_PERCENT_FIELD: UNumberFormatFields = UNumberFormatFields(8);
    pub const UNUM_PERMILL_FIELD: UNumberFormatFields = UNumberFormatFields(9);
    pub const UNUM_SIGN_FIELD: UNumberFormatFields = UNumberFormatFields(10);
    pub const UNUM_MEASURE_UNIT_FIELD: UNumberFormatFields = UNumberFormatFields(11);
    pub const UNUM_COMPACT_FIELD: UNumberFormatFields = UNumberFormatFields(12);
    pub const UNUM_APPROXIMATELY_SIGN_FIELD: UNumberFormatFields = UNumberFormatFields(13);
    pub const UNUM_FIELD_COUNT: UNumberFormatFields = UNumberFormatFields(14);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatFields(pub ::std::os::raw::c_uint);
impl UNumberFormatMinimumGroupingDigits {
    pub const UNUM_MINIMUM_GROUPING_DIGITS_AUTO: UNumberFormatMinimumGroupingDigits =
        UNumberFormatMinimumGroupingDigits(-2);
    pub const UNUM_MINIMUM_GROUPING_DIGITS_MIN2: UNumberFormatMinimumGroupingDigits =
        UNumberFormatMinimumGroupingDigits(-3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatMinimumGroupingDigits(pub ::std::os::raw::c_int);
impl UNumberFormatAttributeValue {
    pub const UNUM_NO: UNumberFormatAttributeValue = UNumberFormatAttributeValue(0);
    pub const UNUM_YES: UNumberFormatAttributeValue = UNumberFormatAttributeValue(1);
    pub const UNUM_MAYBE: UNumberFormatAttributeValue = UNumberFormatAttributeValue(2);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatAttributeValue(pub ::std::os::raw::c_uint);
impl UNumberFormatAttribute {
    pub const UNUM_PARSE_INT_ONLY: UNumberFormatAttribute = UNumberFormatAttribute(0);
    pub const UNUM_GROUPING_USED: UNumberFormatAttribute = UNumberFormatAttribute(1);
    pub const UNUM_DECIMAL_ALWAYS_SHOWN: UNumberFormatAttribute = UNumberFormatAttribute(2);
    pub const UNUM_MAX_INTEGER_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(3);
    pub const UNUM_MIN_INTEGER_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(4);
    pub const UNUM_INTEGER_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(5);
    pub const UNUM_MAX_FRACTION_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(6);
    pub const UNUM_MIN_FRACTION_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(7);
    pub const UNUM_FRACTION_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(8);
    pub const UNUM_MULTIPLIER: UNumberFormatAttribute = UNumberFormatAttribute(9);
    pub const UNUM_GROUPING_SIZE: UNumberFormatAttribute = UNumberFormatAttribute(10);
    pub const UNUM_ROUNDING_MODE: UNumberFormatAttribute = UNumberFormatAttribute(11);
    pub const UNUM_ROUNDING_INCREMENT: UNumberFormatAttribute = UNumberFormatAttribute(12);
    pub const UNUM_FORMAT_WIDTH: UNumberFormatAttribute = UNumberFormatAttribute(13);
    pub const UNUM_PADDING_POSITION: UNumberFormatAttribute = UNumberFormatAttribute(14);
    pub const UNUM_SECONDARY_GROUPING_SIZE: UNumberFormatAttribute = UNumberFormatAttribute(15);
    pub const UNUM_SIGNIFICANT_DIGITS_USED: UNumberFormatAttribute = UNumberFormatAttribute(16);
    pub const UNUM_MIN_SIGNIFICANT_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(17);
    pub const UNUM_MAX_SIGNIFICANT_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(18);
    pub const UNUM_LENIENT_PARSE: UNumberFormatAttribute = UNumberFormatAttribute(19);
    pub const UNUM_PARSE_ALL_INPUT: UNumberFormatAttribute = UNumberFormatAttribute(20);
    pub const UNUM_SCALE: UNumberFormatAttribute = UNumberFormatAttribute(21);
    pub const UNUM_MINIMUM_GROUPING_DIGITS: UNumberFormatAttribute = UNumberFormatAttribute(22);
    pub const UNUM_CURRENCY_USAGE: UNumberFormatAttribute = UNumberFormatAttribute(23);
    pub const UNUM_MAX_NONBOOLEAN_ATTRIBUTE: UNumberFormatAttribute = UNumberFormatAttribute(4095);
    pub const UNUM_FORMAT_FAIL_IF_MORE_THAN_MAX_DIGITS: UNumberFormatAttribute =
        UNumberFormatAttribute(4096);
    pub const UNUM_PARSE_NO_EXPONENT: UNumberFormatAttribute = UNumberFormatAttribute(4097);
    pub const UNUM_PARSE_DECIMAL_MARK_REQUIRED: UNumberFormatAttribute =
        UNumberFormatAttribute(4098);
    pub const UNUM_PARSE_CASE_SENSITIVE: UNumberFormatAttribute = UNumberFormatAttribute(4099);
    pub const UNUM_SIGN_ALWAYS_SHOWN: UNumberFormatAttribute = UNumberFormatAttribute(4100);
    pub const UNUM_LIMIT_BOOLEAN_ATTRIBUTE: UNumberFormatAttribute = UNumberFormatAttribute(4101);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatAttribute(pub ::std::os::raw::c_uint);
impl UNumberFormatTextAttribute {
    pub const UNUM_POSITIVE_PREFIX: UNumberFormatTextAttribute = UNumberFormatTextAttribute(0);
    pub const UNUM_POSITIVE_SUFFIX: UNumberFormatTextAttribute = UNumberFormatTextAttribute(1);
    pub const UNUM_NEGATIVE_PREFIX: UNumberFormatTextAttribute = UNumberFormatTextAttribute(2);
    pub const UNUM_NEGATIVE_SUFFIX: UNumberFormatTextAttribute = UNumberFormatTextAttribute(3);
    pub const UNUM_PADDING_CHARACTER: UNumberFormatTextAttribute = UNumberFormatTextAttribute(4);
    pub const UNUM_CURRENCY_CODE: UNumberFormatTextAttribute = UNumberFormatTextAttribute(5);
    pub const UNUM_DEFAULT_RULESET: UNumberFormatTextAttribute = UNumberFormatTextAttribute(6);
    pub const UNUM_PUBLIC_RULESETS: UNumberFormatTextAttribute = UNumberFormatTextAttribute(7);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatTextAttribute(pub ::std::os::raw::c_uint);
impl UNumberFormatSymbol {
    pub const UNUM_DECIMAL_SEPARATOR_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(0);
    pub const UNUM_GROUPING_SEPARATOR_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(1);
    pub const UNUM_PATTERN_SEPARATOR_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(2);
    pub const UNUM_PERCENT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(3);
    pub const UNUM_ZERO_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(4);
    pub const UNUM_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(5);
    pub const UNUM_MINUS_SIGN_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(6);
    pub const UNUM_PLUS_SIGN_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(7);
    pub const UNUM_CURRENCY_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(8);
    pub const UNUM_INTL_CURRENCY_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(9);
    pub const UNUM_MONETARY_SEPARATOR_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(10);
    pub const UNUM_EXPONENTIAL_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(11);
    pub const UNUM_PERMILL_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(12);
    pub const UNUM_PAD_ESCAPE_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(13);
    pub const UNUM_INFINITY_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(14);
    pub const UNUM_NAN_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(15);
    pub const UNUM_SIGNIFICANT_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(16);
    pub const UNUM_MONETARY_GROUPING_SEPARATOR_SYMBOL: UNumberFormatSymbol =
        UNumberFormatSymbol(17);
    pub const UNUM_ONE_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(18);
    pub const UNUM_TWO_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(19);
    pub const UNUM_THREE_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(20);
    pub const UNUM_FOUR_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(21);
    pub const UNUM_FIVE_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(22);
    pub const UNUM_SIX_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(23);
    pub const UNUM_SEVEN_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(24);
    pub const UNUM_EIGHT_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(25);
    pub const UNUM_NINE_DIGIT_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(26);
    pub const UNUM_EXPONENT_MULTIPLICATION_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(27);
    pub const UNUM_APPROXIMATELY_SIGN_SYMBOL: UNumberFormatSymbol = UNumberFormatSymbol(28);
    pub const UNUM_FORMAT_SYMBOL_COUNT: UNumberFormatSymbol = UNumberFormatSymbol(29);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct UNumberFormatSymbol(pub ::std::os::raw::c_uint);
