name: Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        # test a range of Ruby to ensure gem works
        # keep ruby until EOL. Read more on https://endoflife.date/ruby
        ruby-version:
          - '3.1'
          - '3.2'
          - '3.3'
        runner:
          - ubuntu-22.04
        include:
          # test distributions up to 4 years
          - runner: ubuntu-20.04
            ruby-version: '3.3'
          - runner: ubuntu-24.04
            ruby-version: '3.3'

          # test latest ruby
          - runner: ubuntu-24.04
            ruby-version: head

          # test other platforms
          - runner: windows-2022
            ruby-version: '3.3'

          - runner: macos-13
            ruby-version: '3.3'

          - runner: macos-14
            ruby-version: '3.3'

      fail-fast: false # allow contributors understand failure builds

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake spec
