name: Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        # test a range of Ruby to ensure gem works
        # keep ruby until EOL. Read more on https://endoflife.date/ruby
        ruby-version:
          - '3.2'
          - '3.3'
          - '3.4'
          - '4.0'
        runner:
          - ubuntu-22.04
          - ubuntu-24.04
        include:
          # test latest ruby
          - runner: ubuntu-24.04
            ruby-version: head

          # test other platforms
          - runner: windows-2022
            ruby-version: '4.0'
            allow-failures: true # windows builds are not in active use, but test to unblock contributions

          - runner: macos-14
            ruby-version: '3.4'

          - runner: macos-15
            ruby-version: '3.4'

          - runner: macos-15
            ruby-version: '4.0'

      fail-fast: false # allow contributors understand failure builds

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install ICU on macOS
        if: runner.os == 'macOS'
        run: brew install icu4c

      - name: Run tests
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            export FFI_ICU_LIB="$(brew --prefix icu4c)/lib"
          fi
          bundle exec rake spec
